// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lvwsrwaepgievgqflziq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2d3Nyd2FlcGdpZXZncWZsemlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwODMwMTksImV4cCI6MjA3MzY1OTAxOX0.h2pHAlj3E982KpuJD9IcgLa2iqq8mRIzHdfY3cKznXE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});